package spinoco.fs2.cassandra.macros

import scala.annotation.StaticAnnotation
import scala.language.experimental.macros
import scala.reflect.macros.blackbox

/**
 * Caches labelled generic representation of this class, needed when creating tables out of an annotated case class.
 * This speeds up compilation.
 */
class cacheGeneric extends StaticAnnotation {
  def macroTransform(annottees: Any*): Any = macro CacheGenericMacro.impl
}

// Generated by Claude
object CacheGenericMacro {
  def impl(c: blackbox.Context)(annottees: c.Expr[Any]*): c.Expr[Any] = {
    import c.universe._

    // Helper method to create the cached generic definition
    def createCachedGenericDef(className: TypeName) = {
      val genericName = TermName(s"${className.toString.toLowerCase}Generic")
      q"""
        implicit val $genericName = {
          def cachedGeneric[A](implicit gen: shapeless.LabelledGeneric[A]): gen.type = gen
          cachedGeneric[$className]
        }
      """
    }

    annottees.map(_.tree) match {
      // Case 1: Just the class by itself (no companion)
      case (classDef: ClassDef) :: Nil =>
        val className = classDef.name
        val genericDef = createCachedGenericDef(className)
        val companionObj = q"""
          object ${className.toTermName} {
            $genericDef
          }
        """
        c.Expr[Any](q"""
          $classDef
          $companionObj
        """)

      // Case 2: Class with companion object defined in the same compilation unit
      case (classDef: ClassDef) :: (companionDef: ModuleDef) :: Nil =>
        val className = classDef.name
        val genericDef = createCachedGenericDef(className)

        // Get the companion object name and body
        val ModuleDef(mods, name, Template(parents, self, body)) = companionDef

        // Create a new companion object with our generic definition added
        val newCompanionDef = ModuleDef(
          mods,
          name,
          Template(parents, self, body :+ genericDef)
        )

        c.Expr[Any](q"""
          $classDef
          $newCompanionDef
        """)

      case _ =>
        c.abort(c.enclosingPosition, "@cacheGeneric can only be used with classes or classes with companion objects")
    }
  }
}
