sudo: required

services:
  - docker

language : scala

scala:
  - 2.11.8

cache:
  directories:
  - $HOME/.ivy2
  - $HOME/.sbt

jdk:
  - oraclejdk8

script:
  - sbt ++$TRAVIS_SCALA_VERSION -Dfile.encoding=UTF8 ciBuild

